/**
 * settlementExport — CSV Export module for Settlements, Withdrawals, Commission Records
 *
 * Generates CSV strings from domain data arrays.
 * No Firestore SDK. No side effects. Pure CSV generation.
 *
 * Usage:
 *   const csv = exportSettlementsToCsv(settlements, partnerNames);
 *   downloadCsv(csv, 'settlements-export.csv');
 */

import { fmtDate, fmtDateTime, fmtCurrency } from './firestore';

// ── Download helper ────────────────────────────────────────

export function downloadCsv(csvContent: string, filename: string): void {
  const blob = new Blob(['\ufeff' + csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Trigger a browser print dialog for a printable settlement report.
 */
export function printReport(title: string, contentHtml: string): void {
  const win = window.open('', '_blank');
  if (!win) return;
  win.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; padding: 40px; color: #1f2937; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #e5e7eb; padding-bottom: 20px; }
        .header h1 { font-size: 24px; margin: 0; color: #111827; }
        .header p { font-size: 12px; color: #6b7280; margin: 4px 0 0; }
        .summary { display: flex; gap: 20px; margin-bottom: 24px; flex-wrap: wrap; }
        .summary-item { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px 20px; flex: 1; min-width: 120px; }
        .summary-item .label { font-size: 11px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.5px; }
        .summary-item .value { font-size: 20px; font-weight: 700; color: #111827; margin-top: 2px; }
        table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        th { background: #f3f4f6; text-align: left; padding: 8px 12px; font-size: 11px; text-transform: uppercase; color: #6b7280; border-bottom: 2px solid #e5e7eb; }
        td { padding: 8px 12px; font-size: 13px; border-bottom: 1px solid #f3f4f6; }
        .footer { text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 10px; color: #9ca3af; }
        .footer .page-number { margin-top: 4px; }
        .amount { text-align: right; font-family: 'Courier New', monospace; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>${title}</h1>
        <p>Generated on ${fmtDateTime(new Date().toISOString())}</p>
      </div>
      ${contentHtml}
      <div class="footer">
        <p>Generated by ERP · ${fmtDateTime(new Date().toISOString())}</p>
        <p class="page-number">Page 1</p>
      </div>
      <script>window.onload = function() { window.print(); }</script>
    </body>
    </html>
  `);
  win.document.close();
}

// ── CSV escape ─────────────────────────────────────────────

function esc(value: unknown): string {
  const s = String(value ?? '');
  if (s.includes(',') || s.includes('"') || s.includes('\n')) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}

function csvRow(values: unknown[]): string {
  return values.map(esc).join(',') + '\n';
}

// ═══════════════════════════════════════════════════════════
//  SETTLEMENT EXPORT
// ═══════════════════════════════════════════════════════════

export function exportSettlementsToCsv(
  settlements: any[],
  partnerNames: Record<string, string> = {},
): string {
  let csv = csvRow(['Settlement ID', 'Partner', 'Partner ID', 'Commission Count', 'Total Amount', 'Status', 'Success', 'Skipped', 'Failed', 'Created', 'Completed', 'Wallet TXN']);

  settlements.forEach((s) => {
    csv += csvRow([
      s.id,
      s.partnerName || partnerNames[s.partnerId] || s.partnerId,
      s.partnerId,
      s.commissionCount || 0,
      s.totalAmount || 0,
      s.status || '—',
      s.successCount || 0,
      s.skippedCount || 0,
      s.failedCount || 0,
      fmtDate(s.createdAt),
      fmtDate(s.completedAt),
      s.walletTransactionId || '—',
    ]);
  });

  return csv;
}

// ═══════════════════════════════════════════════════════════
//  WITHDRAWAL EXPORT
// ═══════════════════════════════════════════════════════════

export function exportWithdrawalsToCsv(
  withdrawals: any[],
  partnerNames: Record<string, string> = {},
): string {
  let csv = csvRow([
    'Withdrawal ID', 'Partner', 'Partner ID', 'Amount', 'Status',
    'Payment Method', 'Payment Reference', 'Requested', 'Approved', 'Paid',
    'Rejection Reason', 'Processed By',
  ]);

  withdrawals.forEach((w) => {
    csv += csvRow([
      w.id,
      w.partnerName || partnerNames[w.partnerId] || w.partnerId,
      w.partnerId,
      Math.abs(w.amount || 0),
      w.withdrawalStatus || '—',
      w.paymentMethod || '—',
      w.paymentReference || '—',
      fmtDate(w.withdrawalRequestedAt || w.createdAt),
      fmtDate(w.withdrawalApprovedAt),
      fmtDate(w.withdrawalPaidAt),
      w.withdrawalRejectionReason || '—',
      w.processedBy || '—',
    ]);
  });

  return csv;
}

// ═══════════════════════════════════════════════════════════
//  COMMISSION RECORD EXPORT
// ═══════════════════════════════════════════════════════════

export function exportCommissionRecordsToCsv(
  records: any[],
  leadNames: Record<string, string> = {},
): string {
  let csv = csvRow([
    'Record ID', 'Lead', 'Lead ID', 'Partner ID', 'Deal Value',
    'System Size (kW)', 'Rule', 'Rule Type', 'Amount', 'Approved Amount',
    'Status', 'Generated', 'Approved At', 'Paid At', 'Wallet TXN',
  ]);

  records.forEach((r) => {
    csv += csvRow([
      r.id,
      leadNames[r.leadId] || r.leadId,
      r.leadId,
      r.partnerId,
      r.dealValue || 0,
      r.systemSizeKW || 0,
      r.ruleName || '—',
      r.ruleType || '—',
      r.amount || 0,
      r.approvedAmount || '—',
      r.status || '—',
      fmtDate(r.generatedDate),
      fmtDate(r.approvedAt),
      fmtDate(r.paidAt),
      r.walletTransactionId || '—',
    ]);
  });

  return csv;
}

// ═══════════════════════════════════════════════════════════
//  PARTNER SETTLEMENT STATEMENT (Printable HTML)
// ═══════════════════════════════════════════════════════════

export function generatePartnerStatementHtml(
  partner: any,
  settlements: any[],
  commissionRecords: any[],
  walletTxns: any[],
): string {
  const totalSettled = settlements
    .filter((s) => s.status === 'completed')
    .reduce((sum, s) => sum + (s.totalAmount || 0), 0);
  const totalCommission = commissionRecords.reduce(
    (sum, r) => sum + (r.approvedAmount || r.amount || 0),
    0,
  );
  const totalPaid = walletTxns
    .filter((t) => t.type === 'withdrawal_paid')
    .reduce((sum, t) => sum + Math.abs(t.amount || 0), 0);
  const walletBalance = partner?.walletBalance || 0;
  const pendingBalance = partner?.pendingBalance || 0;

  const settlementRows = settlements
    .map(
      (s) => `
      <tr>
        <td>${s.id}</td>
        <td>${s.commissionCount || 0}</td>
        <td class="amount">${fmtCurrency(s.totalAmount || 0)}</td>
        <td>${s.status || '—'}</td>
        <td>${fmtDate(s.createdAt)}</td>
        <td>${fmtDate(s.completedAt)}</td>
      </tr>`,
    )
    .join('');

  return `
    <div class="summary">
      <div class="summary-item">
        <div class="label">Partner</div>
        <div class="value">${partner?.firmName || partner?.contactPerson || '—'}</div>
      </div>
      <div class="summary-item">
        <div class="label">Wallet Balance</div>
        <div class="value">${fmtCurrency(walletBalance)}</div>
      </div>
      <div class="summary-item">
        <div class="label">Total Commission</div>
        <div class="value">${fmtCurrency(totalCommission)}</div>
      </div>
      <div class="summary-item">
        <div class="label">Total Settled</div>
        <div class="value">${fmtCurrency(totalSettled)}</div>
      </div>
      <div class="summary-item">
        <div class="label">Total Paid</div>
        <div class="value">${fmtCurrency(totalPaid)}</div>
      </div>
      <div class="summary-item">
        <div class="label">Pending Balance</div>
        <div class="value">${fmtCurrency(pendingBalance)}</div>
      </div>
    </div>
    <h3 style="margin-top: 24px; font-size: 16px;">Settlement History</h3>
    <table>
      <thead>
        <tr>
          <th>Settlement ID</th>
          <th>Commissions</th>
          <th class="amount">Amount</th>
          <th>Status</th>
          <th>Created</th>
          <th>Completed</th>
        </tr>
      </thead>
      <tbody>
        ${settlementRows || '<tr><td colspan="6" style="text-align:center;color:#9ca3af;">No settlements found</td></tr>'}
      </tbody>
    </table>
  `;
}

export default {
  downloadCsv,
  printReport,
  exportSettlementsToCsv,
  exportWithdrawalsToCsv,
  exportCommissionRecordsToCsv,
  generatePartnerStatementHtml,
};
