const config = {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        // ── Core (existing) ────────────────────────────────
        foreground: 'var(--color-text)',
        background: 'var(--color-bg)',
        surface: 'var(--color-surface)',
        'surface-hover': 'var(--color-surface-hover)',
        'surface-sunken': 'var(--color-bg-sunken)',
        border: 'var(--color-border)',
        'border-strong': 'var(--color-border-strong)',
        'border-subtle': 'var(--color-border-subtle)',
        primary: 'var(--color-primary)',
        'primary-hover': 'var(--color-primary-hover)',
        'primary-light': 'var(--color-primary-light)',
        'primary-muted': 'var(--color-primary-muted)',
        'primary-text': 'var(--color-primary-text)',
        accent: 'var(--color-accent)',
        'accent-hover': 'var(--color-accent-hover)',
        'accent-light': 'var(--color-accent-light)',
        muted: 'var(--color-text-muted)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-inverse': 'var(--color-text-inverse)',
        'text-disabled': 'var(--color-text-disabled)',
        overlay: 'var(--color-overlay)',
        'focus-ring': 'var(--color-focus-ring)',
        danger: 'var(--color-danger)',
        'danger-light': 'var(--color-danger-light)',
        'danger-text': 'var(--color-danger-text)',
        success: 'var(--color-success)',
        'success-light': 'var(--color-success-light)',
        'success-text': 'var(--color-success-text)',
        warning: 'var(--color-warning)',
        'warning-light': 'var(--color-warning-light)',
        'warning-text': 'var(--color-warning-text)',
        info: 'var(--color-info)',
        'info-light': 'var(--color-info-light)',
        'info-text': 'var(--color-info-text)',

        // ── Sidebar ────────────────────────────────────────
        'sidebar-bg': 'var(--color-sidebar-bg)',
        'sidebar-border': 'var(--color-sidebar-border)',
        'sidebar-active': 'var(--color-sidebar-active)',
        'sidebar-active-text': 'var(--color-sidebar-active-text)',
        'sidebar-item-hover': 'var(--color-sidebar-item-hover)',

        // ── Table tokens (NEW) ────────────────────────────
        'table-header': 'var(--color-table-header-bg)',
        'table-header-text': 'var(--color-table-header-text)',
        'table-header-sort': 'var(--color-table-header-sort)',
        'table-row-hover': 'var(--color-table-row-hover)',
        'table-row-selected': 'var(--color-table-row-selected)',
        'table-row-stripe': 'var(--color-table-row-stripe)',
        'table-checkbox': 'var(--color-table-checkbox)',
        'table-checkbox-bg': 'var(--color-table-checkbox-bg)',
        'table-focus': 'var(--color-table-focus-ring)',
        'pagination-bg': 'var(--color-pagination-bg)',
        'pagination-active': 'var(--color-pagination-active)',
        'pagination-active-text': 'var(--color-pagination-active-text)',
        'pagination-hover': 'var(--color-pagination-hover)',
        'table-footer': 'var(--color-table-footer-bg)',
        'table-scrollbar': 'var(--color-table-scrollbar)',
        'selection-bar': 'var(--color-table-selection-bar)',
      },
    },
  },
};

export default config;
