import type React from 'react';
import { Plus, Trash2 } from 'lucide-react';
import { Button, Input, Select, Textarea } from '../../../components/ui';
import { fmtCurrency } from '../../../lib/firestore';
import type { PurchaseOrderFormValues, PurchaseOrderItemForm, VendorRecord } from '../types';
import { PURCHASE_ORDER_ITEM_DEFAULT } from '../types';
import type { ProjectRecord } from '../../projects/types';

function previewTotals(items: PurchaseOrderItemForm[]) {
  return items.reduce((totals, item) => { const gross = (Number(item.qty) || 0) * (Number(item.price) || 0); const taxable = Math.max(0, gross - (Number(item.discount) || 0)); const tax = taxable * (Number(item.tax) || 0) / 100; return { subtotal: totals.subtotal + taxable, tax: totals.tax + tax, total: totals.total + taxable + tax }; }, { subtotal: 0, tax: 0, total: 0 });
}

export function PurchaseOrderForm({ value, vendors, products, projects, currencySymbol, onChange, onSubmit, onCancel, saving }: { value: PurchaseOrderFormValues; vendors: VendorRecord[]; products: any[]; projects?: ProjectRecord[]; currencySymbol: string; onChange: (value: PurchaseOrderFormValues) => void; onSubmit: (event: React.FormEvent) => void; onCancel: () => void; saving: boolean }) {
  const patch = (next: Partial<PurchaseOrderFormValues>) => onChange({ ...value, ...next });
  const updateItem = (index: number, next: Partial<PurchaseOrderItemForm>) => patch({ items: value.items.map((item, itemIndex) => itemIndex === index ? { ...item, ...next } : item) });
  const selectProduct = (index: number, productId: string) => { const product = products.find((entry) => entry.id === productId); updateItem(index, product ? { productId, product: product.name || product.productName || '', description: product.description || '', hsn: product.hsn || product.hsnCode || '', unit: product.unit || product.uom || 'Nos', price: String(product.purchasePrice ?? product.costPrice ?? product.price ?? ''), tax: String(product.tax ?? product.gst ?? 0) } : { ...PURCHASE_ORDER_ITEM_DEFAULT }); };
  const totals = previewTotals(value.items);
  return <form className="space-y-5" onSubmit={onSubmit}>
    <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Select label="Vendor *" required value={value.vendorId} onChange={(event) => patch({ vendorId: event.target.value })} options={[{ label: 'Select vendor…', value: '' }, ...vendors.map((vendor) => ({ label: `${vendor.name}${vendor.gstin ? ` · ${vendor.gstin}` : ''}`, value: vendor.id }))]} /><Select label="Project (optional)" value={value.projectId} onChange={(event) => patch({ projectId: event.target.value })} options={[{ label: 'No project', value: '' }, ...(projects || []).map((project) => ({ label: project.projectId || project.id, value: project.id }))]}           /><Input label="Order Date *" required type="date" value={value.orderDate} onChange={(event) => patch({ orderDate: event.target.value })} /><Input label="Expected Delivery *" required type="date" value={value.expectedDeliveryDate} onChange={(event) => patch({ expectedDeliveryDate: event.target.value })} /></div>
    <div className="space-y-3"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold text-[var(--color-text)]">Line Items</h3><Button type="button" size="xs" variant="outline" icon={<Plus className="h-3.5 w-3.5" />} onClick={() => patch({ items: [...value.items, { ...PURCHASE_ORDER_ITEM_DEFAULT }] })}>Add Item</Button></div>
      {value.items.map((item, index) => <div key={index} className="rounded-xl border border-[var(--color-border-subtle)] bg-[var(--color-bg-sunken)] p-3"><div className="grid gap-3 md:grid-cols-12"><div className="md:col-span-4"><Select label="Product *" value={item.productId} onChange={(event) => selectProduct(index, event.target.value)} options={[{ label: 'Select product…', value: '' }, ...products.map((product) => ({ label: product.name || product.id, value: product.id }))]} /></div><div className="md:col-span-2"><Input label="Quantity" type="number" min="0.01" step="0.01" value={item.qty} onChange={(event) => updateItem(index, { qty: event.target.value })} /></div><div className="md:col-span-2"><Input label="Unit Price" type="number" min="0" step="0.01" value={item.price} onChange={(event) => updateItem(index, { price: event.target.value })} /></div><div className="md:col-span-1"><Input label="Tax %" type="number" min="0" max="100" value={item.tax} onChange={(event) => updateItem(index, { tax: event.target.value })} /></div><div className="md:col-span-2"><Input label="Discount" type="number" min="0" step="0.01" value={item.discount} onChange={(event) => updateItem(index, { discount: event.target.value })} /></div><div className="flex items-end md:col-span-1"><Button type="button" variant="ghost" icon={<Trash2 className="h-4 w-4" />} disabled={value.items.length === 1} onClick={() => patch({ items: value.items.filter((_, itemIndex) => itemIndex !== index) })} aria-label={`Remove line ${index + 1}`} /></div></div></div>)}
    </div>
    <div className="ml-auto w-full max-w-sm space-y-2 rounded-xl border border-[var(--color-border-subtle)] p-4 text-sm"><div className="flex justify-between"><span>Taxable subtotal</span><b>{fmtCurrency(totals.subtotal, currencySymbol)}</b></div><div className="flex justify-between"><span>Tax</span><b>{fmtCurrency(totals.tax, currencySymbol)}</b></div><div className="flex justify-between border-t border-[var(--color-border)] pt-2 text-base"><span>Total</span><b>{fmtCurrency(totals.total, currencySymbol)}</b></div></div>
    <Textarea label="Notes" value={value.notes} onChange={(event) => patch({ notes: event.target.value })} />
    <div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={onCancel}>Cancel</Button><Button type="submit" loading={saving}>Save Draft</Button></div>
  </form>;
}
