import {DEMO_CLEANUP_CONFIRMATION,DEMO_COMPANY_ID,DEMO_FORBIDDEN_FIELD_PATTERN,DEMO_MAX_DELETIONS,DEMO_MAX_MUTATIONS,DEMO_RESET_CONFIRMATION,DEMO_SEED_ID,configuredProjectAllowlist} from './config.ts';
import type {DemoCliOptions,DemoDocument,ExistingDocument} from './types.ts';
export function parseDemoCliOptions(argv=process.argv.slice(2),env=process.env):DemoCliOptions{const c=argv.find(a=>a.startsWith('--confirm='));return{apply:argv.includes('--apply'),confirm:c?.slice(10),allowedProjects:configuredProjectAllowlist(env)}}
export function assertProjectAllowed(projectId:string,allowed:string[]){if(!projectId||!allowed.length||!allowed.includes(projectId))throw new Error(`Firebase project "${projectId||'(missing)'}" is not explicitly allowlisted. Set DEMO_ALLOWED_FIREBASE_PROJECTS.`)}
export function assertMutationMode(o:DemoCliOptions){if(!o.apply)throw new Error('Dry-run mode: no writes are allowed without explicit --apply.')}
export function assertDestructiveConfirmation(k:'reset'|'cleanup',o:DemoCliOptions){assertMutationMode(o);const e=k==='reset'?DEMO_RESET_CONFIRMATION:DEMO_CLEANUP_CONFIRMATION;if(o.confirm!==e)throw new Error(`${k} requires --confirm=${e}`)}
export function assertMutationCeiling(n:number,c=DEMO_MAX_MUTATIONS){if(!Number.isInteger(n)||n<0||n>c)throw new Error(`Mutation plan count ${n} exceeds safety ceiling ${c}.`)}
export function assertDeletionCeiling(n:number,c=DEMO_MAX_DELETIONS){if(!Number.isInteger(n)||n<0||n>c)throw new Error(`Deletion plan count ${n} exceeds safety ceiling ${c}.`)}
export function isAuthorizedDemoRecord(d:Record<string,unknown>|undefined){return d?.companyId===DEMO_COMPANY_ID&&d?.isDemo===true&&d?.demoSeedId===DEMO_SEED_ID}
export function assertNoForeignCollision(doc:DemoDocument,e:ExistingDocument){if(!e.exists)return;const d=e.data||{};if(doc.collection==='user_auth_maps'){if(d.userId===doc.data.userId&&d.companyId===DEMO_COMPANY_ID&&d.email===doc.data.email)return;throw new Error(`Foreign auth mapping collision at user_auth_maps/${doc.id}.`)}if(!isAuthorizedDemoRecord(d))throw new Error(`Unmarked deterministic ID collision at ${doc.collection}/${doc.id}.`)}
export function assertSafeDeleteDocument(doc:DemoDocument){if(doc.data.companyId!==DEMO_COMPANY_ID||doc.data.demoSeedId!==DEMO_SEED_ID||doc.data.isDemo!==true)throw new Error(`Refusing unsafe delete candidate ${doc.collection}/${doc.id}.`)}
export function findForbiddenFields(v:unknown,p='$'):string[]{if(!v||typeof v!=='object')return[];return Object.entries(v as Record<string,unknown>).flatMap(([k,c])=>{const q=`${p}.${k}`;return[...(DEMO_FORBIDDEN_FIELD_PATTERN.test(k)?[q]:[]),...findForbiddenFields(c,q)]})}
export function assertNoForbiddenFields(docs:DemoDocument[]){const v=docs.flatMap(d=>findForbiddenFields(d.data).map(p=>`${d.collection}/${d.id}:${p}`));if(v.length)throw new Error(`Forbidden secret/identity fields detected: ${v.join(', ')}`)}
export function redactForLog(v:unknown){return JSON.stringify(v,(k,c)=>DEMO_FORBIDDEN_FIELD_PATTERN.test(k)?'[REDACTED]':c,2)}
