import { useCallback, useMemo } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { Activity, ArrowLeft, Building2, FolderKanban, Hammer, Zap } from 'lucide-react';
import { Button } from '../components/ui/Button';
import { PageHeader } from '../components/ui/Card';
import { WorkspaceShell, useWorkspace } from '../components/shared';
import type { TabId } from '../components/shared/WorkspaceTabs';
import { MONITORING_TABS } from '../features/monitoring/utils/workspaceConfig';
import { useGenerationReading } from '../features/monitoring/hooks/useGenerationReadings';
import type { GenerationReadingRecord } from '../lib/monitoringWorkflow';
import { COLLECTIONS } from '../lib/firebase';
import { getAll } from '../lib/firestore';
import { useAppStore } from '../store/useAppStore';
import { usePermissions } from '../lib/permissions';

const field = (label: string, value: React.ReactNode) => <div className="rounded-lg border border-[var(--color-border-subtle)] bg-[var(--color-bg-sunken)] p-3"><p className="text-[11px] font-bold uppercase text-[var(--color-text-muted)]">{label}</p><p className="mt-1 text-sm font-medium text-[var(--color-text)]">{value || '—'}</p></div>;
export default function MonitoringWorkspace() {
  const { id = '' } = useParams<{ id: string }>(); const navigate = useNavigate(); const companyId = useAppStore(s => s.activeCompanyId); const perms = usePermissions(); const workspace = useWorkspace('generation_reading', id, 'overview'); const activeTab = workspace.activeTab as TabId;
  const { data: record, isLoading } = useGenerationReading(id);
  const related = useQuery({ queryKey: ['monitoring-related', companyId, record?.projectId], enabled: Boolean(record?.projectId), queryFn: async () => { const [projects, installations, commissioning, amc, tickets] = await Promise.all([getAll<any>(COLLECTIONS.PROJECTS), getAll<any>('installations'), getAll<any>(COLLECTIONS.COMMISSIONING_RECORDS), getAll<any>(COLLECTIONS.AMC_CONTRACTS), getAll<any>(COLLECTIONS.SERVICE_TICKETS)]); const project = projects.find(p => p.id === record?.projectId); return { project, installation: installations.find(x => x.projectId === record?.projectId), commissioning: commissioning.find(x => x.projectId === record?.projectId), amc: amc.find(x => x.id === record?.amcContractId || x.projectId === record?.projectId), ticket: tickets.find(x => x.id === record?.linkedServiceTicketId || x.projectId === record?.projectId) }; } });
  const onNavigate = useCallback((path: string) => navigate(path), [navigate]);
  if (isLoading) return <WorkspaceShell loading />;
  if (!record) return <div className="flex min-h-[50vh] flex-col items-center justify-center gap-3"><Zap className="h-10 w-10 text-[var(--color-text-muted)]"/><p>Generation reading not found.</p><Button variant="outline" onClick={() => navigate('/monitoring')}>Back to Monitoring</Button></div>;
  const links = related.data; const project = links?.project;
  const overview = <div className="space-y-5 p-5"><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{field('Generation', `${record.readingKwh} kWh`)}{field('Reading date', record.readingDate)}{field('Recorded by', record.recordedByName || record.recordedBy)}{field('Reading ID', record.id)}</div><section className="rounded-xl border border-[var(--color-border-subtle)] bg-[var(--color-surface)] p-4"><h2 className="text-sm font-semibold">Lifecycle relationships</h2><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" icon={<FolderKanban className="h-3.5 w-3.5"/>} onClick={() => onNavigate(`/projects/${record.projectId}`)}>Project</Button>{project?.customerId && <Button size="sm" variant="outline" icon={<Building2 className="h-3.5 w-3.5"/>} onClick={() => onNavigate(`/customers/${project.customerId}`)}>Customer</Button>}{links?.installation && <Button size="sm" variant="outline" icon={<Hammer className="h-3.5 w-3.5"/>} onClick={() => onNavigate(`/installations/${links.installation.id}`)}>Installation</Button>}{links?.commissioning && <Button size="sm" variant="outline" onClick={() => onNavigate(`/commissioning/${links.commissioning.id}`)}>Commissioning</Button>}{links?.amc && <Button size="sm" variant="outline" onClick={() => onNavigate(`/amc-contracts/${links.amc.id}`)}>AMC</Button>}{links?.ticket && <Button size="sm" variant="outline" icon={<Activity className="h-3.5 w-3.5"/>} onClick={() => onNavigate(`/service-tickets/${links.ticket.id}`)}>Service Ticket</Button>}</div></section>{record.notes && <section className="rounded-xl border border-[var(--color-border-subtle)] bg-[var(--color-surface)] p-4"><h2 className="text-sm font-semibold">Notes</h2><p className="mt-2 whitespace-pre-wrap text-sm">{record.notes}</p></section>}<p className="text-xs text-[var(--color-text-muted)]">This generation reading is immutable. Corrections require a new reading with an explanatory note.</p></div>;
  return <div className="flex h-full min-h-0 flex-col"><PageHeader title="Monitoring" icon={<Activity className="h-5 w-5"/>} actions={<Button size="sm" variant="outline" icon={<ArrowLeft className="h-4 w-4"/>} onClick={() => navigate('/monitoring')}>Monitoring</Button>}/><WorkspaceShell header={{ name: `${record.readingKwh} kWh`, status: 'Recorded', entityId: record.id, createdAt: record.createdAt, assignedTo: record.recordedByName ? { name: record.recordedByName } : undefined }} tabs={{ tabs: MONITORING_TABS, activeTab, onTabChange: tab => workspace.setActiveTab(tab as any), overview, tabProps: { entityId: record.id, entityType: 'generation_reading', companyId: companyId || '', record: record as unknown as Record<string, unknown>, permissions: { canView: perms.canView('projects'), canCreate: perms.canCreate('projects'), canEdit: false, canDelete: false }, caseId: (record as any).caseId } }}/></div>;
}