import { CompanyConfig } from '../../../config/company';
import { getDocumentTheme } from '../shared/theme';
import { getPrintStyles } from '../shared/styles';
import { renderCompanyCustomerBlock, renderTermsBlock } from '../shared/blocks';
import { fmtDate } from '../../../lib/firestore';
import { b64ToSrc } from '../shared/utils';

export function renderDispatchChallan(company: CompanyConfig, dispatchData: any) {
  const theme = getDocumentTheme(company.companyCode || 'CGPL');
  
  const meta = [
    { label: 'Document Type', value: 'DELIVERY CHALLAN' },
    { label: 'Challan No', value: dispatchData.id },
    { label: 'Date', value: fmtDate(dispatchData.date || dispatchData.createdAt) },
    { label: 'Order Ref', value: dispatchData.orderId || '—' },
  ];

  let itemsHtml = `
    <thead>
      <tr>
        <th style="width:5%;text-align:center;">S.No</th>
        <th style="width:40%;">Description of Goods</th>
        <th style="width:15%;text-align:center;">HSN/SAC</th>
        <th style="width:10%;text-align:center;">Qty</th>
        <th style="width:30%;">Tracking Information (Serials)</th>
      </tr>
    </thead>
    <tbody>
  `;

  let totalQty = 0;

  (dispatchData.items || []).forEach((it: any, i: number) => {
    const qty = Number(it.verifiedQty || it.qty) || 0;
    totalQty += qty;
    
    const trackingStr = (it.serials || []).join(', ') || (it.barcodes || []).join(', ') || 'N/A';

    itemsHtml += `
      <tr>
        <td class="text-center">${i + 1}</td>
        <td><b>${it.product}</b></td>
        <td class="text-center">${it.hsn || '—'}</td>
        <td class="text-center font-bold">${qty} <span style="font-weight:normal;font-size:9px;">${it.unit||'PCS'}</span></td>
        <td style="font-family:monospace;font-size:9px;word-break:break-all;">${trackingStr}</td>
      </tr>
    `;
  });

  itemsHtml += `
    <tr>
      <td colspan="3" class="text-right font-bold">Total Quantity:</td>
      <td class="text-center font-bold">${totalQty}</td>
      <td></td>
    </tr>
  </tbody>`;

  const signSrc = b64ToSrc(company.signature);

  const footerHtml = `
    <div style="display:flex; border-top:1px solid var(--border);">
      <div style="width:33.33%; padding:10px; border-right:1px solid var(--border);">
        <div style="font-weight:700; color:var(--primary); margin-bottom:40px; font-size:10px;">Receiver's Signature & Seal</div>
        <div style="border-top:1px solid var(--border); padding-top:3px; font-size:9px;">Date & Time</div>
      </div>
      <div style="width:33.33%; padding:10px; border-right:1px solid var(--border);">
        <div style="font-weight:700; color:var(--primary); margin-bottom:40px; font-size:10px;">Driver's Signature</div>
        <div style="border-top:1px solid var(--border); padding-top:3px; font-size:9px;">Name: ${dispatchData.driverName || '—'}</div>
      </div>
      <div style="width:33.33%; padding:10px; text-align:center;">
        <div style="font-weight:700; color:var(--primary); margin-bottom:5px; font-size:10px;">Authorized Signatory</div>
        ${signSrc ? `<img src="${signSrc}" style="max-height:35px;max-width:100px;object-fit:contain;margin-bottom:5px;" />` : '<div style="height:35px;"></div>'}
        <div style="border-top:1px solid var(--border); padding-top:3px; font-size:9px;">For ${company.name}</div>
      </div>
    </div>
  `;

  return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>Challan - ${dispatchData.id}</title>
      <style>${getPrintStyles(theme)}</style>
    </head>
    <body>
      <div class="a4-container">
        <div class="doc-header">DELIVERY CHALLAN</div>
        ${renderCompanyCustomerBlock(company, dispatchData, meta)}
        <table>${itemsHtml}</table>
        ${renderTermsBlock(dispatchData.notes)}
        ${footerHtml}
      </div>
      <div style="text-align:center; font-size:9px; color:#666; margin-top:5px; padding-bottom:10px;">
        Generated by Neozy ERP on ${new Date().toLocaleString('en-IN')}
      </div>
    </body>
    </html>
  `;
}
