import {describe,expect,it} from 'vitest';
import {assertDemoCapability,demoPolicySummary,isCanonicalDemoIdentity,isDemoCapabilityAllowed} from '../demoCapabilityPolicy';
import {DEMO_COMPANY_ID,DEMO_ERP_USER_ID} from '../../config/demo';
import {createLease,DEMO_RESET_LEASE_MS,type ResetLease} from '../../../scripts/demo/resetLease.ts';
import {buildCompleteDemoPlan} from '../../../scripts/demo/datasets/complete.ts';
import {verifyPlan} from '../../../scripts/demo/verify.ts';
import {assertTenantSafeUploadPath} from '../demoUploadPolicy';
import {useAppStore} from '../../store/useAppStore';
import {readFileSync} from 'node:fs';

describe('final public Demo hardening',()=>{
 it('centralizes interactive and blocked capabilities',()=>{expect(isDemoCapabilityAllowed(DEMO_COMPANY_ID,'business-crud')).toBe(true);expect(isDemoCapabilityAllowed(DEMO_COMPANY_ID,'company-scoped-upload')).toBe(true);for(const cap of ['company-admin','user-admin','role-admin','integration-secrets','external-side-effect','owner-ai','system-counter','audit-mutation','stock-ledger-mutation','demo-reset'] as const){expect(isDemoCapabilityAllowed(DEMO_COMPANY_ID,cap)).toBe(false);expect(()=>assertDemoCapability(DEMO_COMPANY_ID,cap)).toThrow('public demo')}expect(isDemoCapabilityAllowed('production-company','integration-secrets')).toBe(true);expect(demoPolicySummary().blocked).toContain('owner-ai')});
 it('recognizes only the canonical Demo identity',()=>{expect(isCanonicalDemoIdentity({companyId:DEMO_COMPANY_ID,id:DEMO_ERP_USER_ID,isDemo:true})).toBe(true);expect(isCanonicalDemoIdentity({companyId:DEMO_COMPANY_ID,id:'OTHER'})).toBe(false)});
 it('permits only canonical upload prefixes for Demo',()=>{useAppStore.setState({activeCompanyId:DEMO_COMPANY_ID,user:{id:DEMO_ERP_USER_ID,companyId:DEMO_COMPANY_ID} as any});expect(()=>assertTenantSafeUploadPath(`companies/${DEMO_COMPANY_ID}/surveys/x/file.jpg`)).not.toThrow();expect(()=>assertTenantSafeUploadPath(`users/${DEMO_ERP_USER_ID}/profile/avatar.jpg`)).not.toThrow();expect(()=>assertTenantSafeUploadPath('surveys/x/file.jpg')).toThrow('company-scoped')});
 it('refuses overlapping reset leases and recovers stale leases',()=>{const now=new Date('2026-07-13T00:00:00Z'),active=createLease('run-a',now);expect(Date.parse(active.expiresAt)-now.getTime()).toBe(DEMO_RESET_LEASE_MS);expect(()=>createLease('run-b',new Date(now.getTime()+1000),active)).toThrow('already running');const stale={...active,expiresAt:new Date(now.getTime()-1).toISOString()} as ResetLease;expect(createLease('run-b',now,stale).owner).toBe('run-b');expect(createLease('run-c',now,{...active,status:'failed'}).owner).toBe('run-c')});
 it('keeps the complete graph UI-compatible at high-risk boundaries',()=>{const plan=buildCompleteDemoPlan('AUTH');expect(verifyPlan(plan)).toEqual([]);for(const collection of ['leads','customers','projects','quotations','orders','proforma_invoices','payments','purchase_orders','stock','dispatch','qc_checks','commissioning_records','tasks','notifications'])expect(plan.documents.some(d=>d.collection===collection)).toBe(true);expect(plan.documents.filter(d=>d.collection==='projects').every(d=>Array.isArray(d.data.stageHistory)&&d.data.name&&d.data.customerId)).toBe(true);expect(plan.documents.filter(d=>d.collection==='engineering_designs').every(d=>d.data.systemCapacityKw&&d.data.revisionNumber===1)).toBe(true);expect(plan.documents.filter(d=>d.collection==='commissioning_records').every(d=>typeof d.data.generationTestKwh==='number')).toBe(true);expect(plan.documents.filter(d=>d.collection==='generation_readings').every(d=>typeof d.data.readingKwh==='number'&&d.data.recordedBy)).toBe(true);expect(plan.documents.filter(d=>d.collection==='tasks').every(d=>d.data.assignedToId&&d.data.createdBy)).toBe(true);expect(plan.documents.filter(d=>d.collection==='notifications').every(d=>Array.isArray(d.data.visibleTo)&&d.data.body&&typeof d.data.isRead==='boolean')).toBe(true)});
 it('keeps scheduled reset trusted, guarded and non-concurrent',()=>{const workflow=readFileSync('.github/workflows/demo-reset.yml','utf8');expect(workflow).toMatch(/schedule:/);expect(workflow).toMatch(/workload_identity_provider/);expect(workflow).toMatch(/concurrency:/);expect(workflow).toContain('npm run demo:seed');expect(workflow).toContain('--confirm=RESET-company-demo-neozy');expect(workflow).not.toMatch(/password/i)});
 it('protects reset operational records in Firestore rules',()=>{const rules=readFileSync('firestore.rules','utf8');expect(rules).toMatch(/match \/demo_operations\/\{documentId\}[\s\S]*allow read, write: if false/)});
});
